### ISSUE TITLE
[db] 클릭 횟수 테이블 고민

### ISSUE THREAD

**Issue by JunHoPark93** [URL-CHOP/Chop-Api#19]
<img width="505" alt="screen shot 2019-01-14 at 10 53 34 am" src="https://user-images.githubusercontent.com/20608121/51093820-b4865780-17ea-11e9-910b-f71963ab9d6c.png">

- 그림처럼 클릭할때마다 Insert.
아니면
- totalCnt(총클릭수)두고 클릭할 때마다 Update

어느 쪽이 좋을까요

**Comment by JunHoPark93** [comment]
update로 진행하겠습니다!

**Comment by aj1155** [comment]
클릭 할때마다 insert하면 row수 불필요하게 많아지지 않을까요 ㅋㅋ
우리 disk가 감당이되려나
