### ISSUE TITLE
[리팩토링] 3주차 리뷰 리팩토링

### ISSUE THREAD

**Issue by JunHoPark93** [URL-CHOP/Chop-Api#31]
- [x] UrlValidator에 regex final로 설정, isValid에 인자 네이밍 수정, 안 쓰는 Override 지우기
- [x] String matches말고 pattern, matcher 활용하기
- [x] ErrorInfo 클래스 네이밍 변경 고민
- [x] ApiExceptionHandler에서 RuntimeException 추가
- [x] Integration Test 작성
- [x] Null 처리 부분 Optional 고려
- [x] line 정리

**Comment by aj1155** [comment]
굿굿 좋습니다
