### ISSUE TITLE
[개발] Url 단축 서버측 알고리즘 개발

### ISSUE THREAD

**Issue by JunHoPark93** [URL-CHOP/Chop-Api#4]
- Base62 사용하기
- 테스트 코드 작성하기

**Comment by aj1155** [comment]
음 base62단축 알고리즘과, mysql연동은 기능을 나눠서 작업 하는게 좋아보이네요~~
한 번에 너무 많은 작업을 하기 보다는
기능을 조금 더 세분화, 작게 해서 feature를 만들어 봅시다

**Comment by JunHoPark93** [comment]
넵! 알겠습니다! 그럼 혹시 처음 커밋할때 h2를 추가해서 올려도될까요? 그 후에 의존성 삭제하고 mysql 연동하는 형태로 바꿔도 될까용??

**Comment by aj1155** [comment]
넹
