### ISSUE TITLE
[Referer] 특정 조건

### ISSUE THREAD

**Issue by choitaehoon** [URL-CHOP/Chop-Api#40]
<h1>Referer 특정 조건</h1>

<li>리퍼러는 반드시 하이퍼링크를 통해서 방문 했을때만 가져올 수 있다.</li>
<li>웹브라우저에서 바로 URL 입력하거나 즐겨찾기를 통해 들어온 경우 리퍼러를 알 수 없다</li>
<li>리퍼러를 전송 받지 못하는 경우는 보통 다이렉트 접속에 받질 못한다</li>
<hr>

<ul>
<li>리퍼러가 없는 경우 </li>
    <ul><li>직접 주소 입력, 북 마크 입력, 플래시로 만든 광고 등등...</li></ul>
</ul>

<ul>
<li>리퍼러가 있는 경우</li>
     <ul><li>웹사이트 링크, 검색 엔진, 이메일 등등...</li></ul>
</ul>

**Comment by JunHoPark93** [comment]
https://www.nexters.me/a

**Comment by choitaehoon** [comment]
nexters.me/1b
