### ISSUE TITLE
[URL 단축 고민] 알고리즘 내부 구현

### ISSUE THREAD

**Issue by choitaehoon** [URL-CHOP/Chop-Api#5]
<ul>
<li>서버 캐시 기능</li><ul>
            <li>서버 하나 만든 후에 지금 현재 조회한 id 값을 캐싱하여 편리하게 가져오기 -> 태훈 생각</li></ul>
</ul>

<p><p>

<ul>
<li>시간으로 해싱</li><ul>
             <li>서버, 디비에서 뭔가 id를 계속 체크 할 경우 문제가 생길 수 있기 때문에 시간을 이용해서 구하기 -> 만기형 생각</li>
</ul>
</ul>

<ul>
<li>UUID 랜덤값 이용하기</li><ul>
               <li>UUID를 이용하여 고유한 값이 생성 되므로 UUID에 대해 문자나 특수 문자를 지우기 ->준호형 생각</li>
</ul>
<p><p>
일단 더 생각해 봐야 될거 같다.

**Comment by aj1155** [comment]
굿굿 좋네요!
