### ISSUE TITLE
[db schema] 디비 설계

### ISSUE THREAD

**Issue by choitaehoon** [URL-CHOP/Chop-Api#8]
![nextersdb](https://user-images.githubusercontent.com/33123391/50732445-f6961480-11be-11e9-810d-032f8bcba5ec.png)

<h3>테이블 : user</h3>
<ul>
     <li>id (고유 id)</li>
     <li>name (유저 이름)</li>
     <li>password (유저 비밀번호)</li>
     <li>address (주소)</li>
</ul>

<h3>테이블 :  url</h3>
<ul>
     <li>id (고유 id)</li>
     <li>create_time (생성 시간)</li>
     <li>long_Url (초기 URL)</li>
     <li>shortUrl (줄여준 URL)</li>
     <li>total_count (총 클릭 횟수)</li>
     <li>user_id (user 의 fk)</li>
              <ul>
              <li>유저가 없을 수 있으므로 null 허용</li>
              </ul>
     <li>statistics_user_id (statistics_user의 fk)</li>
               <ul>
               <li>통계를 사용하지 않은 유저가 있을 수 있으므로 null 허용</li>
               </ul>
</ul>

<h3>테이블 : statistics_url</h3>
<ul>
     <li>id (고유 id)</li>
     <li>url_click_time (URL클릭 시간)</li>
     <li>url_click_time_count (url 클릭 한 시간의 총 횟수)</li>
           <ul>
                 <li>날마다 클릭한 횟수가 다르므로</li>
           </ul>
     <li>url_id (url의 fk)</li>
           <ul>
                <li>url_id 정보 가져오기 위해서 사용</li>
           </ul>
</ul>

<h3>테이블 : statistics_user</h3>
<ul>
     <li>id (고유 id)</li>
     <li>user_click_time (유저 클릭 시간)</li>
     <li>user_click_count (유저 해당 url 클릭 횟수)</li>
</ul>

초기 작업

**Comment by aj1155** [comment]
오케이 태훈아 고생했어 수요일에 또 얘기해보자

**Comment by JunHoPark93** [comment]
통계 서버, 디비 따로 두기로 결정
