### ISSUE TITLE
[think] url 단축에 대해

### ISSUE THREAD

**Issue by choitaehoon** [URL-CHOP/Chop-Api#84]
<li>url 단축을 하게 되면 유효성을 검사하게 된다. 그런데 지금 코드를 보면 예를 들어 https://book.naver.com를 하게 되면 유효성에 체크가 되지 않지만 book.naver.com를 하게 되면 유효한 url이 아니라고 나온다. 이 정규식을 바꾸고 리다이렉트해서 HttpStatus.ok가 되면 유효성에서 벗어나게 해줘야 할꺼 같은 생각이 든다
</li>

**Comment by aj1155** [comment]
url이라 하믄 https, http가 앞에 붙는게 나는 맞다고 보는데~
실제 니 말처럼 
book.naver.com 이런 류의 문자들이 서버에 유입되면 오히려나는 이 부분에대해 처리하는 로직이 더 복잡할거라고 생각이들어
이거는 고민을 더 해봤으면 한다

**Comment by choitaehoon** [comment]
비틀리에서는 저런방식으로도 되서 생각해봤습니다 더 생각해보겠습니다!
